# config/config.yaml
astar:
  heuristic_weight: 1.0
  max_iterations: 1000

lane_detection:
  model_path: "models/lane_detection_model.h5"

lidar:
  max_range: 100.0
  angle_resolution: 0.1

behavior_planner:
  param_name: param_value

aeb_system:
  safety_threshold: 0.5
  alert_level: high

astar_pathfinding:
  grid_size: 50
  max_iterations: 1000

# Add more parameters for each node as needed

